### ISSUE TITLE
Do you happen to know what the license was on these?

### ISSUE THREAD

**Issue by andlabs** [pauldotknopf/WindowsSDK7-Samples#1]
I can't seem to find a source that says what the licenses are; Microsoft's own github account doesn't have these and the licensing info I can find only counts for Windows 8 samples and newer. I'm also not usre if the DirectX-based ones are different — I'm interested in the license of the DirectWrite ChooseFont sample. Thanks.

**Comment by pauldotknopf** [comment]
I'm sorry, but I'm not sure.

I may not be allowed to have the source publicly available, but given Microsoft's recent attitude change, I doubt they'll care ;)

**Comment by andlabs** [comment]
They probably don't care seeing as MSDN got rid of the Windows 7 samples from the public documentation to begin with =P Oh well, I guess I can still use the sample code as a reference while I write my own. Thanks in the meantime though!
