### ISSUE TITLE
ffmpeg with AecSDKDemo

### ISSUE THREAD

**Issue by PeadarO** [pauldotknopf/WindowsSDK7-Samples#6]
Good afternoon Mr Knopf,
    I hope you don't mind my writing to you directly. I am working on the development of a chatroom to help minority languages. It will have live video and sound. I would like to use a program you wrote but I am having an issue with it. Baron Bi on Msdn Social recommended that I write to you.
    The chatroom is in Visual C++ using holepunched sockets, a Linux Server with 'c', DirectShow and ffmpeg. I will be implementing WINE to run it on Android and such. I have most of it working for quite some time now. When I put the whole thing together it worked but there was an awful echo, especially when the person at the far end had a laptop, since on the laptop the mike and speakers are very close together.
    I found your AecSDKDemo on the internet and I compiled and ran it. I runs great. I can send the voice from it over to another computer through a holepunched socket and it sounds perfect.  I can also get the sound directly from the mike, compress it with ffmpeg, send it over and then decompress and play it. That's perfect too. The problem arises when I try to compress and decompress the output from AecSDKDemo. The compressor acts like it is working, no errors and the compressed data goes over through the socket. The decompressor acts like it is working too. Still no errors but I don't get any sound. I've tried everything; giving it loads of extra memory, dividing the AecSDKDemo output string into thousand-byte lengths and sending them separately etc. I have compared the output from your program with the raw output from the mike and they seem to be quite similar - each byte being between -127 and +128 but still one will compress/decompress and the other will not.
    I have tried contacting the ffmpeg users group but after writing to them quite a few times I never got any reply. I can send you whatever code you would like to see. If you would like to speak live on Skype we can certainly arrange that. I'm in Ireland and we have the same time as the UK.
    Thank you in advance for any help and if we can get to the bottom of this I'll certainly post the solution on MSDN social or GitHub as I am sure it will apply to anyone who wants to use the AecSDKDemo program for live sound.

    Again, Thank you in advance.

        Peadar O'Colmain, Dublin ,Ireland, Tue, 17 04 2018

**Comment by pauldotknopf** [comment]
I don't support the code here.
