### ISSUE TITLE
reference to a wrong project name in readme file

### ISSUE THREAD

**Issue by sumantfordev** [pauldotknopf/WindowsSDK7-Samples#7]
https://github.com/pauldotknopf/WindowsSDK7-Samples/tree/master/security/authentication/sampssp

In the above page, i found 2 issues
1. The sample ssp contains a make file that builds in Windows NT systems only and fails in a windows 7 machine, making this not usable under a windows SDK 7 sample

2. The readme file contains a help documentation on how to invoke after building it using a SOCKAUTH security.c file, howevere i could not find a reference to that in this github.
Can anyone please help

**Comment by pauldotknopf** [comment]
This repo only contains a copy of the files delivered as apart of the Windows SDK.

No support is given for the contents, it's only a reference.

**Comment by sumantfordev** [comment]
yes, i created it in microsoft github page
