### ISSUE TITLE
AecSDKDemo doesn't work on some computers. 

### ISSUE THREAD

**Issue by PeadarO** [pauldotknopf/WindowsSDK7-Samples#9]
Hello Mr Knopf,
I am having a problem with AECSDKDemo and I would very much appreciate any input from you or anyone else. I'll certainly share the solution.
I am using your AecSDKDemo program and it has worked very well for me for quite some time.
Unfortunately I am now trying it on a different  computer and when I run  it the 
PCM file that it creates contains only a scratchy noise.
As before, I am listening to the PCM file by importing it into Audacity as raw data.
I went to the microsoft website and downloaded the AecSDKDemo program again. 
I have not changed anything in the code so I am definitely using precisely your code.
I have included it in a VC++ project which I created as a console application.
I have used the same computer and microphone to record my voice with Audacity.
The Audacity recording plays perfectly.
When I load the PCM file into Audacity I use mostly the default values. (I change the speed down to 8000)

The computer is a Vostro 200  (Dell)
with Windows 10 Pro
Processor Intel Core (TM)2 Duo CPU2.33 Ghz
Installed memory 4.00 GB (3.24 GB usable)
System type 32 bit Operating system x64-based processor

Any opinion or help greatly appreciated.

Peadar

**Comment by pauldotknopf** [comment]
I don't support the code here.
